feat: busext push 消息时添加超时机制
shanbay/gobay pull request #322
Opened 2021-07-12 10:43 UTC by hj24

- 防止 bus 卡死导致一个消息 push 不了影响其它消息 push

2021-08-03 02:17 UTC, fenngwd requested changes

2021-08-03 02:17 UTC, fenngwd commented on extensions/busext/amqp_test.go
> +	assert.Len(t, result, 100)
@hj24 we need test after timeout we still could push without failure?

2021-08-03 02:17 UTC, fenngwd commented on extensions/busext/amqp.go
> +		err := b.unsafePush(exchange, routingKey, data)
@hj24 we should clean b.channel state.

2021-08-04 06:45 UTC, hj24 commented on extensions/busext/amqp_test.go
> +	assert.Len(t, result, 100)
这个我直接 mock 了 push 的方法，让它 sleep 超过我们的超时时间，可能不太好测超时之后继续 push 的情况

2021-08-04 07:33 UTC, hj24 commented on extensions/busext/amqp.go
> +		err := b.unsafePush(exchange, routingKey, data)
这里直接清空这个 channel ？

2021-08-05 11:35 UTC, hj24 commented on extensions/busext/amqp.go
> +		b.notifyChanBlock <- errTimeout
handleReconnect 里已经实现了重连，所以这里直接加了个 channel 通知它就可以了

2021-08-05 16:45 UTC, fenngwd commented on extensions/busext/amqp.go
> +		case <-b.notifyChanBlock:
@hj24 handleReconnect 在第一次连接完成之后，就退出了吧？这里这么加入，没有goroutine来接受吧

2021-08-05 16:45 UTC, fenngwd commented on extensions/busext/amqp_test.go
> +	err = bus.Push("sbay-exchange", routingKey, *msg)
为什么这里第二次就能Push成功了？

2021-08-05 16:45 UTC, fenngwd commented on extensions/busext/amqp_test.go
> +		dur := 100 * bus.pushTimeout
@hj24 这里光sleep应该还不足够模拟卡死的情况，可以尝试把channel的状态改掉来模拟只能进来一次的错误情况，
```
if b.channel == nil {
    return fmt.Errorf("channel is not initialized")
}
b.channel = nil
dur := 100 * bus.pushTimeout
...
```

2021-08-05 16:50 UTC, fenngwd commented
@hj24 t

2021-08-06 01:36 UTC, hj24 commented on extensions/busext/amqp.go
> +		case <-b.notifyChanBlock:
第一次完成连接之后没有退出，而是阻塞在这个 select 这，等待接收到 done 或者 notifyConnClose 才会退出，或者 notifyChanClose 和新加的 notifyChanBlock 这个选择重新 init

2021-08-06 01:38 UTC, hj24 commented on extensions/busext/amqp_test.go
> +	err = bus.Push("sbay-exchange", routingKey, *msg)
第一次 errTimeout 之后通知 handleReConnect 重连了，所以 sleep 一会儿之后就能重新 push 了

2021-08-06 03:40 UTC, fenngwd commented on extensions/busext/amqp_test.go
> +	err = bus.Push("sbay-exchange", routingKey, *msg)
我的意思是这里Task内容没有发生变化，再次Push不是还会在Task里面去Sleep吗？

2021-08-06 05:41 UTC, hj24 commented on extensions/busext/amqp_test.go
> +	err = bus.Push("sbay-exchange", routingKey, *msg)
我把 publish 方法的初始化方进 init 里了，所以再次 init，publish 会被换成新 channel 的方法

2021-08-06 05:49 UTC, hj24 commented on extensions/busext/amqp_test.go
> +		dur := 100 * bus.pushTimeout
这里每次进来的时候都会拿锁，模拟最里面的 amqp publish sleep，只要它不释放，应该就可以只能进来一次吧？

2021-08-06 08:41 UTC, fenngwd commented on extensions/busext/amqp_test.go
> +		dur := 100 * bus.pushTimeout
Push方法收到Done信号退出后，自动就释放掉了pushM，无论goroutine 持有的channel的状态是怎么样的。所以push超时之后，没有验证到channel的reconnect操作的效果。

2021-08-06 15:22 UTC, hj24 commented on extensions/busext/amqp_test.go
> +		dur := 100 * bus.pushTimeout
这个 mock 方法里没办法取到 b.channel，不过要实现这个只能进来一次，可以把对 b.isReady 的判断提到最前面，这样就可以在 Push 触发重连后到重连完成前只能有这么一次 Push，其它时候都会返回 err

2021-08-09 02:10 UTC, hj24 commented on extensions/busext/amqp_test.go
> +		dur := 100 * bus.pushTimeout
这个可以合了吗

2021-08-09 08:59 UTC, fenngwd approved these changes
/LGTM

2021-08-09 08:59 UTC, merged