asynctask health check
shanbay/gobay pull request #343
Opened 2021-08-16 09:19 UTC by sljeff

- 改用 `shanbay/amqp`
- 增加 asynctask ext 的健康检查
    - 使用方法：`curl 127.0.0.1:9000/health?timeout=5&queue=gobay.task_sub`

2021-08-17 05:57 UTC, sljeff commented
@fenngwd @nicholasxuu

2021-08-17 06:23 UTC, nicholasxuu commented on extensions/asynctaskext/asynctaskext.go
> +	t.lock.Lock()
为什么要加lock？

2021-08-17 06:42 UTC, sljeff commented on extensions/asynctaskext/asynctaskext.go
> +	t.lock.Lock()
同时起两次 `StartWorker` 的时候，避免 `t.workers` append 的时候出现 DATA RACE 的报错，以及加锁保证 `t.healthHandlerRegistered` 的修改是对的。

> 不过如果真的在同一个进程里同时调两次 `StartWorker` 还是会在 `worker.Luanch` 的时候出现别的 DATA RACE 报错（应该是在 machinery 那个库里），所以测试里面起一个 StartWorker 的 goroutine 完了会 sleep 确保他跑完再起另一个 worker。

2021-08-17 14:57 UTC, fenngwd requested changes

2021-08-17 14:57 UTC, fenngwd commented on extensions/asynctaskext/asynctaskext.go
> +		t.healthSrv = &http.Server{Addr: ":9000"}
HTTP API 改为5000

2021-08-17 14:57 UTC, fenngwd commented on extensions/asynctaskext/asynctaskext.go
> +	t.lock.Unlock()
defer Unlock

2021-08-17 14:57 UTC, fenngwd commented on extensions/asynctaskext/asynctaskext.go
> +	timeoutS, err := strconv.Atoi(params["timeout"][0])
这个变量名字是什么意思？timeoutS

2021-08-18 02:45 UTC, sljeff commented on extensions/asynctaskext/asynctaskext.go
> +	t.lock.Unlock()
下面的 worker.Luanch 是阻塞的，所以只能写在这里了

2021-08-18 02:45 UTC, sljeff commented on extensions/asynctaskext/asynctaskext.go
> +	timeoutS, err := strconv.Atoi(params["timeout"][0])
意思是这个变量的单位是秒……

2021-08-18 06:33 UTC, fenngwd commented on extensions/asynctaskext/asynctaskext.go
> +	t.lock.Unlock()
阻塞的话，那这个方法还可以被调多次吗？

2021-08-18 06:35 UTC, sljeff commented on extensions/asynctaskext/asynctaskext.go
> +	t.lock.Unlock()
我们生产使用的时候没有调多次的，都是一个进程是一个 wroker；但是测试里就是一个进程起两个 worker 的例子（两个 goroutine 分别起的）

2021-08-18 06:36 UTC, sljeff commented on extensions/asynctaskext/asynctaskext.go
> +	t.lock.Unlock()
应该说现在的写法是没有禁止一个进程起两个 worker 的

2021-08-18 07:07 UTC, fenngwd approved these changes
LGTM

2021-08-18 07:08 UTC, merged