Feature http retry
shanbay/gobay pull request #359
Opened 2021-11-09 01:59 UTC by Ithrael

2021-11-11 10:24 UTC, hj24 requested changes

2021-11-11 10:24 UTC, hj24 commented on extensions/stubext/ext_test.go
> +func TestStubExtServerStopRetryLongerUh(t *testing.T) {
用 assert 库写单元测试

2021-11-11 10:25 UTC, hj24 requested changes

2021-11-11 10:25 UTC, hj24 commented on extensions/stubext/ext.go
>  import (
commit 压缩一下

2021-11-15 10:11 UTC, Ithrael commented
@fenngwd

2021-11-15 11:05 UTC, fenngwd requested changes

2021-11-15 11:05 UTC, fenngwd commented on extensions/stubext/ext.go
> +func uhInterceptor() grpc.UnaryClientInterceptor {
uhInterceptor => newUHInterceptor

2021-11-15 11:06 UTC, fenngwd commented
@Ithrael

2021-11-15 11:08 UTC, fenngwd requested changes

2021-11-15 11:08 UTC, fenngwd commented on extensions/stubext/ext_test.go
> +		//if !ok {
删掉无用代码

2021-11-15 11:08 UTC, fenngwd commented on extensions/stubext/ext_test.go
> +	"github.com/stretchr/testify/assert"
goimports

2021-11-15 11:08 UTC, fenngwd commented on extensions/stubext/ext.go
>  			grpc.WithChainStreamInterceptor(grpc_retry.StreamClientInterceptor(callOpts...)),
stream也需要

2021-11-16 09:29 UTC, fenngwd approved these changes
LGTM

2021-11-16 10:56 UTC, merged