stub 添加x-down-stream-name头
shanbay/gobay pull request #364
Opened 2021-12-09 04:24 UTC by Mrgrtt

添加x-down-stream-name头，值为pod的HOSTNAME环境变量前缀，用于识别调用方
![image](https://user-images.githubusercontent.com/34758567/145334145-623eeb78-522f-4231-84ca-c6c27d2c7ed9.png)

2021-12-09 05:57 UTC, hj24 requested changes
检查一下代码，合并上游的改动

2021-12-09 05:57 UTC, hj24 commented on cmd/gobay/templates/app/asynctask/server.go.tmpl
> +	if err := myapp.AsyncTask.StartWorker("", 10); err != nil {
这个 pr 有问题吧，很多代码是旧的？

2021-12-14 02:17 UTC, hj24 requested changes

2021-12-14 02:17 UTC, hj24 commented on extensions/stubext/interceptor_test.go
> +	//md, ok := metadata.FromIncomingContext(ctx)
这些注释可以去掉吧

2021-12-14 02:17 UTC, hj24 commented on go.mod
> +	google.golang.org/protobuf v1.26.0-rc.1
go mod tidy 过了吗？

2021-12-14 02:39 UTC, sljeff commented
1. CI没跑，我看 health_pb2 删掉了一大段是没有影响的么（还有 health_pb2_mock 最好也一起生成下吧）
2. 我感觉这个叫 DownSteamNameHeaderInterceptor 的函数讲不太通（为什么下游名字就是 HOSTNAME 按 - 切开取到倒数第三个？），我觉得注释写的更清楚些，写明就是给 k8s pod 用的，而且这个拦截器的名字也应该体现出来是 k8s pod 使用的；或者干脆放到 gordon 里而不是这个开源项目里。

2021-12-14 07:15 UTC, Mrgrtt commented
> 
重新生成的 health_pb2，本地测试可以跑通
注释加上了

2021-12-16 08:32 UTC, closed without merging