rm cachenil
shanbay/gobay pull request #370
Opened 2021-12-16 10:57 UTC by sljeff

原来的 cachenil 逻辑有错误，会导致实际上只有一种情况会返回 cachext.Nil，即命中了 cache 且 cache 里存的是 msgpack nil 值；其他情况都不会。详见这里 https://github.com/shanbay/gobay/pull/363

---

如果改回正确的响应值，会和现状产生一个比较大的差异：改完了以后即使没有 WithCacheNil 同样可能返回 `cachext.Nil`。

而我们使用时都没有做过这个处理，改动起来会很大，所以干脆删除掉这个逻辑，让使用者自行判断值是不是空值，这样改动会小得多。

2021-12-31 03:35 UTC, sljeff commented
@fenngwd

2022-01-04 13:26 UTC, fenngwd requested changes

2022-01-04 14:49 UTC, sljeff commented on docs/CHANGELOG.md
> +# 0.17.1 (2021-12-16)
你说的「主版本号」是指哪一种：
1. 这个 PR 合入打成 v1.0.0
3. 这个 PR 合入以后，在包路径里加上 `/v1`

2022-01-05 01:52 UTC, fenngwd commented on docs/CHANGELOG.md
> +# 0.17.1 (2021-12-16)
第二种和第一种不是互斥的，第二种引入后也是需要打v1的git tag

2022-01-05 02:19 UTC, sljeff commented on docs/CHANGELOG.md
> +# 0.17.1 (2021-12-16)
我感觉旧的用法不需要持续维护的话（比如这个改动），没有啥必要在包路径里加 `v1` `v2` 这种用法吧，用版本号足够区分了。

2022-01-05 06:33 UTC, fenngwd commented on docs/CHANGELOG.md
> +# 0.17.1 (2021-12-16)
嗯，那就先升级tag。

2022-01-05 08:52 UTC, sljeff commented on docs/CHANGELOG.md
> +# 0.17.1 (2021-12-16)
更新了 CHANGELOG，改成了 1.0.0

2022-01-07 02:54 UTC, merged